apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  volumes:
    - name: out
      hostPath:
        path: /tmp/out
        type: Directory
  templates:
    - name: blender-export
      script:
        image: nytimes/blender:2.92-cpu-ubuntu18.04
        command: [bash]
        source: |
            apt update -y
            apt install -y -qq xvfb unzip wget zip
            DRI_PRIME=0 xvfb-run --auto-servernum blender --background --python /tmp/out/run.py
        volumeMounts:
          - mountPath: /tmp/out
            name: out
    - name: artifact-example
      dag:
        tasks:
          - name: generate-artifact
            template: blender-export
