name: "Build workflow"
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get VRM addon
      run: |
        wget -L https://github.com/saturday06/VRM_Addon_for_Blender/archive/refs/tags/1_13_0.zip
    - name: Update OS
      run: |
        uname -a
        sudo apt install -y -q xvfb unzip wget flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.blender.Blender -y
        sudo flatpak override org.blender.Blender --talk-name=org.freedesktop.Flatpak
    - name: Blend
      run: |
        DRI_PRIME=0 xvfb-run --auto-servernum flatpak run org.blender.Blender --background --python `pwd`/run.py -- `pwd`
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: V-Sekai Blue Tin Fox Models (VRM) 
        path: result/*.vrm        
    - uses: actions/upload-artifact@v2
      with:
        name: V-Sekai Blue Tin Fox Models (glTF2) 
        path: result/*.glb
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DDTHH-MM-SSZ
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: V-Sekai_Models.zip
        path: result
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: V-Sekai Blue Tin Fox Models ${{ steps.current-time.outputs.formattedTime }}
        files: |
          LICENSE
          V-Sekai_Models.zip