name: "Build workflow"
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get VRM addon
      run: |
        wget -L https://github.com/saturday06/VRM_Addon_for_Blender/archive/refs/tags/1_11_0.zip
    - name: Update OS
      run: |
        uname -a
        sudo apt install -y -qq xvfb unzip wget
        sudo apt install -y flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.blender.Blender -y
        sudo flatpak override org.blender.Blender --talk-name=org.freedesktop.Flatpak
    - name: Blend
      run: |
        DRI_PRIME=0 xvfb-run --auto-servernum flatpak run org.blender.Blender --background --python `pwd`/run.py -- `pwd`
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: V-Sekai Blue Tin Fox Models (VRM) 
        path: result/*.vrm        
    - uses: actions/upload-artifact@v2
      with:
        name: V-Sekai Blue Tin Fox Models (glTF2) 
        path: result/*.glb