name: "Build workflow"
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get VRM addon
      run: |
        wget -L https://github.com/saturday06/VRM-Addon-for-Blender/releases/download/2_14_17/VRM_Addon_for_Blender-2_14_17.zip
    - name: Update OS
      run: |
        uname -a
        sudo apt install -y -q xvfb unzip wget flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.blender.Blender -y
        sudo flatpak override org.blender.Blender --talk-name=org.freedesktop.Flatpak
    - name: Blend
      run: |
        DRI_PRIME=0 xvfb-run --auto-servernum flatpak run org.blender.Blender --background --python `pwd`/run.py -- `pwd`
      shell: bash
    - name: Copy license
      run: |
        cp LICENSE blockmesh/
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: V-Sekai Blue Tin Fox Models (VRM) 
        path: blockmesh/*.vrm        
    - uses: actions/upload-artifact@v2
      with:
        name: V-Sekai Blue Tin Fox Models (glTF2) 
        path: blockmesh/*.glb
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: V-Sekai_Models.zip
        path: blockmesh/*
          LICENSE
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: true
        title: V-Sekai Blue Tin Fox Models
        files: |
          V-Sekai_Models.zip