name: "Build workflow"
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get VRM addon
      run: |
        wget -L https://github.com/saturday06/VRM_Addon_for_Blender/archive/refs/tags/1_11_0.zip
    - name: Update OS
      run: |
        uname -a
        sudo apt update -y
        sudo apt install -y -qq xvfb unzip wget flatpak
        sudo flatpak install flathub org.blender.Blender
    - name: Blend
      run: |
        DRI_PRIME=0 xvfb-run --auto-servernum flatpak run org.blender.Blender --background --python run.py
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: V-Sekai Blue Tin Fox Models 
        path: result
    - name: Release
      # if: startsWith(github.ref, 'refs/tags/')
      run: |
        ./gh_cli/gh release create --prerelease `echo ./generate_tag.sh` ${{ env.FILES }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILES: result