name: "Build workflow"
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: nytimes/blender:2.92-cpu-ubuntu18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get VRM addon
      run: |
        wget -L https://github.com/saturday06/VRM_Addon_for_Blender/archive/refs/tags/1_11_0.zip
    - name: Update OS
      run: |
        uname -a
        apt update -y
        apt install -y -qq xvfb unzip wget
    - name: Blend
      run: |
        DRI_PRIME=0 xvfb-run --auto-servernum blender --background --python run.py
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: V-Sekai Blue Tin Fox Models 
        path: result
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          result
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}