name: "Build workflow"
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: dockerhub-username:docker-image-tag
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get host
      run: |
        uname -a
        apt update -y
        apt install -y -qq xvfb unzip wget zip
        DRI_PRIME=0 xvfb-run --auto-servernum blender --background --python run.py
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: V-Sekai Blue Tin Fox Models 
        path: result